In [1]:
import numpy as np

Write a “function” m-file called zscore1 that scales a data matrix so that each column has a unit variance and zero mean and returns the scaling parameters (mean and standard deviation).

In [2]:
def zscore1(x):
    means = np.mean(x, axis=0)
    stds = np.std(x, axis=0)

    xs = (x - means[np.newaxis, :]) / stds[np.newaxis, :]

    return xs, means, stds

## Create a matrix of random test data that meets the criteria above [sic]

"generate a matrix of random test data with 4 variables (columns) and 20 observations (rows). **Each column should have a different mean and standard deviation**."

In [3]:
means = np.random.randint(100, size=4)
stds = np.random.randint(100, size=4)
print(f'Means:\t{means}\n'
      f'Stds:\t{stds}')

Means:	[56 59 26 79]
Stds:	[41 89 87 82]


In [4]:
x = np.random.randn(20, 4)
x = (x * stds[np.newaxis, :]) + means[np.newaxis, :]
print(x)

[[  81.97872012  262.39794313  -20.54081847   49.02232236]
 [  23.10888748  -39.83676434  139.49528058   80.44426904]
 [   7.01938763   -2.56516069  -16.30432222   12.81275072]
 [  31.03721713  118.72725126   46.17633453  184.82719221]
 [  81.0576051   145.44875754   81.20749627  111.25392181]
 [  72.92329611  -36.98267391   49.82523581  -57.36656922]
 [ -14.96941455  -54.31770777   81.87236673   80.34789761]
 [  87.15165403   67.57952044   21.21701085   71.41868841]
 [  40.30659039    7.24685416  127.44042432  316.34990049]
 [   8.00709333    8.16317024   78.20359787   64.2711651 ]
 [  93.19058451  -73.61194529   98.54099942   70.65968925]
 [  63.71598878  221.35721038   -9.68757349   56.91578947]
 [  23.33697539  240.48801988   -4.83663602  120.62924749]
 [  83.3239407   266.95946776  -24.50743851   62.06656755]
 [  -5.52407743  151.80993746   84.81115589  208.14389772]
 [  57.85111409  143.60404909   88.95300427  139.38141115]
 [ -65.18255248   -7.24267748  117.69497951  242.2592143

## Call the `zscore1` function to give the calculated standardized data matrix, mean vector, and standard deviation vector.

In [5]:
xs, xmeans, xstds = zscore1(x)
print(xs)
print(f'Means:\t{xmeans}')
print(f'Stds:\t{xstds}')

[[  8.19332873e-01   1.67719392e+00  -1.32879776e+00  -7.15537842e-01]
 [ -4.99968703e-01  -1.16603353e+00   1.68980078e+00  -3.26117962e-01]
 [ -8.60542219e-01  -8.15406534e-01  -1.24888903e+00  -1.16429193e+00]
 [ -3.22290981e-01   3.25633547e-01  -7.03798013e-02   9.67525166e-01]
 [  7.98690238e-01   5.77012090e-01   5.90377455e-01   5.57136092e-02]
 [  6.16396418e-01  -1.13918410e+00  -1.55427904e-03  -2.03404143e+00]
 [ -1.35332197e+00  -1.30226082e+00   6.02918232e-01  -3.27312317e-01]
 [  9.35260837e-01  -1.55531020e-01  -5.41162197e-01  -4.37974193e-01]
 [ -1.14559818e-01  -7.23101483e-01   1.46242226e+00   2.59751830e+00]
 [ -8.38407254e-01  -7.14481378e-01   5.33717968e-01  -5.26555200e-01]
 [  1.07059621e+00  -1.48376845e+00   9.17321736e-01  -4.47380655e-01]
 [  4.10056183e-01   1.29110942e+00  -1.12408401e+00  -6.17712171e-01]
 [ -4.94857143e-01   1.47107962e+00  -1.03258570e+00   1.71904316e-01]
 [  8.49479920e-01   1.72010578e+00  -1.40361609e+00  -5.53877317e-01]
 [ -1.

## Visually compare the calculated mean and standard deviation vectors to those you expect (based on how you generated your random test data).

Not very close to our true values. It may be that our sample is not large enough to be representative. To test, try larger sample (say, 2000000 rows).

In [6]:
y = np.random.randn(2000000, 4)
y = (y * stds[np.newaxis, :]) + means[np.newaxis, :]

In [7]:
ys, ymeans, ystds = zscore1(y)
print(f'Means:\t{ymeans}')
print(f'Stds:\t{ystds}')

Means:	[ 55.98381515  58.93500643  25.90269363  79.01524845]
Stds:	[ 40.99823858  88.98156703  87.05420662  82.0168006 ]


Much better!

## Check the mean and standard deviation of the columns in xs.

In [8]:
np.mean(xs, axis=0)

array([  7.49400542e-17,  -3.05311332e-17,   6.66133815e-17,
         2.08340289e-16])

Very close to zero (thanks to floating point precision)

In [9]:
np.std(xs, axis=0)

array([ 1.,  1.,  1.,  1.])

Precisely at unity (I don't know why these values don't suffer from floating point precision problems)