In [16]:
import numpy as np
import numpy.linalg as la
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from scipy.spatial.distance import cdist

In [11]:
PCR = Pipeline([
    ('poly', PolynomialFeatures()),
    ('scale', StandardScaler()),
    ('pca', PCA()),
    ('linear', LinearRegression())
])

In [13]:
x = np.ones((4, 2))
y = np.sum(x, axis=1)
print(x)
print(y)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[ 2.  2.  2.  2.]


In [15]:
np.polyfit(x, y, deg=1)

TypeError: expected 1D vector for x

In [17]:
x = np.random.rand(10).reshape((-1, 2))

In [20]:
x1 = np.array([[1, 2]])

In [21]:
cdist(x, x1)

array([[ 1.81272711],
       [ 1.6777826 ],
       [ 1.26729801],
       [ 1.66009267],
       [ 1.85265372]])

In [59]:
from scipy.integrate import trapz
def f(x, d=4.0):
    c = 1 / (2 - 1/d)
    if np.abs(x) < d:
        return c*(1 - np.abs(x) / d)
    else:
        return 0

In [60]:
x = np.linspace(-1, 1, 1000000)

In [61]:
fv = np.vectorize(f)

In [62]:
trapz(fv(x), x)

0.99999999999985711

In [63]:
f(4)

0

In [64]:
f(3)

0.14285714285714285

In [65]:
f(3.9999)

1.4285714285744433e-05

In [66]:
f(0)

0.5714285714285714

In [67]:
f(-1)

0.42857142857142855

In [68]:
f(2)

0.2857142857142857

In [69]:
1. - 3.9999 / 4.0

2.5000000000052758e-05