In [7]:
from __future__ import division
import numpy as np
from uncertainties import ufloat
import uncertainties

In [8]:
from uncertainties.umath import *

In [9]:
def deadtime_corrected(r, dt=267e-6):
    return r / (1 - r * dt)

In [10]:
crs = np.array([ufloat(53,2)])

In [11]:
crs

array([53.0+/-2.0], dtype=object)

In [12]:
deadtime_corrected(crs)

array([53.760768636981936+/-2.0578285827263083], dtype=object)

In [13]:
def countrate(counts, time, backgroundcounts, bgtime):
    return counts / time - backgroundcounts / bgtime

In [14]:
def meas(count):
    return ufloat(count, count ** 0.5)

In [18]:
counts = np.array([meas(i) for i in np.array([17612., 4548., 1357., 746., 501.])])
counts

array([17612.0+/-132.71021060943275, 4548.0+/-67.43886120034946,
       1357.0+/-36.837480912787726, 746.0+/-27.313000567495326,
       501.0+/-22.38302928559939], dtype=object)

In [21]:
time = np.array([
        190.8, 200, 200, 200, 200
    ])
time = np.array(
    [ufloat(i, 0.) for i in time]
)
time

array([190.8+/-0, 200.0+/-0, 200.0+/-0, 200.0+/-0, 200.0+/-0], dtype=object)

In [22]:
countrate(counts, time, 171., 300.)

array([91.73607966457023+/-0.6955461771982848,
       22.169999999999998+/-0.3371943060017473,
       6.215+/-0.18418740456393864, 3.16+/-0.13656500283747663,
       1.935+/-0.11191514642799696], dtype=object)

In [29]:
dtcr = deadtime_corrected(countrate(counts, time, 171., 300.))

In [24]:
a = ufloat(5., 1.)

In [25]:
a.error_components

<bound method Variable.error_components of 5.0+/-1.0>

In [26]:
a.error_components()

{5.0+/-1.0: 1.0}

In [27]:
a.nominal_value

5.0

In [28]:
a.s

1.0

In [30]:
[e.s for e in dtcr]

[0.7309129600786,
 0.3412220020770382,
 0.1848002124866649,
 0.13679574006119963,
 0.11203087690928655]

In [32]:
cs_initial_activity = ufloat(10., 0.05 * 10)
def activity(initial, time, halflife):
    l = np.log(2) / halflife
    return initial * np.exp(-l * time)
activity(cs_initial_activity, 74, 30.08 * 12)

8.675333562110444+/-0.43376667810552216

In [34]:
co_initial_activity = sum([ufloat(1., 0.05) for i in range(4)])
co_initial_activity

4.0+/-0.1

In [36]:
activity(co_initial_activity, 57., 5.27*12)

2.141574293538566+/-0.053539357338464155