# NE597: Linear Algebra Homework \#1

In [1]:
import numpy as np

## 1.3

In [2]:
A = np.matrix(
    [
        [8, 0, -3, 4],
        [5, 5, 8, -7],
        [3, -2, -1, 0],
        [0, 7, 5, 4]
    ]
)
B = np.matrix(
    [
        [-3, 1, 1, 10],
        [3, 4, 15, 12],
        [0, -4, -8, 9],
        [2, 1, 1, 2]
    ]
)

### a

In [3]:
2*A

matrix([[ 16,   0,  -6,   8],
        [ 10,  10,  16, -14],
        [  6,  -4,  -2,   0],
        [  0,  14,  10,   8]])

### b

In [4]:
A + B

matrix([[ 5,  1, -2, 14],
        [ 8,  9, 23,  5],
        [ 3, -6, -9,  9],
        [ 2,  8,  6,  6]])

### c

In [5]:
A*B

matrix([[-16,  24,  36,  61],
        [-14, -14,   9, 168],
        [-15,  -1, -19,  -3],
        [ 29,  12,  69, 137]])

### d

In [6]:
B - A

matrix([[-11,   1,   4,   6],
        [ -2,  -1,   7,  19],
        [ -3,  -2,  -7,   9],
        [  2,  -6,  -4,  -2]])

### e

In [7]:
B*A

matrix([[-16,  73,  66,  21],
        [ 89,  74,  68,  32],
        [-44,  59,  21,  64],
        [ 24,  17,  11,   9]])

### f

In [9]:
A.trace()

matrix([[16]])

### g

In [10]:
B.trace()

matrix([[-5]])

### h

In [12]:
np.trace(A ** 2 * B)

1809

## 1.16

Let $\mathbf{A}$ be an $n \times n$ matrix and let $\mathbf{B}=\mathbf{A} + \mathbf{A}^T$ and $\mathbf{C} = \mathbf{A} - \mathbf{A}^T$. Show that:

1. $\mathbf{B}$ is symmetric and $\mathbf{C}$ is skew-symmetric.
2. Every $n \times n$ matrix can be represented as a sum of a symmetric and skew-symmetric matrix.

## 1.17

For each of the following pairs of matrices, find an elementary matrix $\mathbf{E}$ such that $\mathbf{EA}=\mathbf{B}$.

### a

In [15]:
A = np.matrix([
    [3, 8],
    [5, 16]
])
B = np.matrix([
    [12, 32],
    [5, 16]
])

### b

In [16]:
A = np.matrix([
    [7, 6, 3],
    [2, 0, 9],
    [-8, 7, 4]
])
B = np.matrix([
    [-8, 7, 4],
    [2, 0, 9],
    [7, 6, 3]
])

### c

In [17]:
A = np.matrix([
    [1, 4, 5, 9],
    [0, 6, 2, 1],
    [-4, 5, 2, -3],
    [3, -3, 9, 0]
])
B = np.matrix([
    [1, 4, 5, 9],
    [6, 0, 20, 1],
    [-4, 5, 2, -3],
    [3, -3, 9, 0]
])

## 1.27