In [1]:
import numpy as np
import numpy.linalg as la

Caculate $\mu_n$

In [2]:
mu1 = .2182179
quadrature = 8

In [3]:
@np.vectorize
def mu_n(n, mu1=mu1, quad=quadrature):
    c = 2 * (1 - 3 * mu1 ** 2) / (quad - 2)
    mu_n_squared = mu1**2 + (n-1) * c
    return mu_n_squared ** 0.5

In [4]:
inds = np.arange(1, 5)

In [5]:
mus = mu_n(inds)
print(mus)

[ 0.2182179   0.57735027  0.78679579  0.95118973]


In [6]:
integrals = np.array([1 / (2 * (l + 1)) for l in [0, 2, 4, 6, 8]])

In [7]:
integrals

array([ 0.5       ,  0.16666667,  0.1       ,  0.07142857,  0.05555556])

In [8]:
ells = np.arange(2, 13, 2)
ells

array([ 2,  4,  6,  8, 10, 12])

In [9]:
def row(l, mus):
    m1 = mus[0]
    m2 = mus[1]
    m3 = mus[2]
    m4 = mus[3]
    r = [
        2*m1**l + m4**l,
        2*m1**l + 2*m2**l + 2*m3**l,
        m2**l,
    ]
    return r

In [10]:
mat = np.array([row(n, mus) for n in [0, 2, 4, 6, 8]])

In [11]:
mat

array([[ 3.        ,  6.        ,  1.        ],
       [ 1.        ,  2.        ,  0.33333333],
       [ 0.82312924,  0.99319727,  0.11111111],
       [ 0.7408487 ,  0.54875282,  0.03703704],
       [ 0.67010657,  0.3184167 ,  0.01234568]])

In [12]:
2*la.inv(mat.T @ mat) @ mat.T @ integrals

array([ 0.12098766,  0.09074074,  0.09259259])

These match the values in the book, table 4-1