In [1]:
import pandas as pd
import numpy as np
import numpy.linalg as la

/Users/jrpowers-luhn/miniconda3/envs/579/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/jrpowers-luhn/miniconda3/envs/579/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


# Find the $\lambda$, $B^2$, and $\alpha$ eigenvalues for infinite medium cross sections

In [15]:
m = np.array([
    [1, 0.0055, 0.072, 2, 2.2e9, 0.07, 0, 0],
    [0, 0.068, 0.20, 0.7, 3.2e8, 0, 0.13, 0],
    [0, 2.48, 2.02, 0.2, 2.7e7, 0, 0, 0.58],
    [0, 2.00, 1.0, 0.3, 2.5e5, 0, 0, 0]
])
cols = ['chi', 'nu-sigma_f', 'sigma-a', 'D', 'v', 's->1', 's->2', 's->3']
df = pd.DataFrame(m, columns=cols)

In [16]:
df

chi  nu-sigma_f  sigma-a    D             v  s->1  s->2  s->3
0  1.0      0.0055    0.072  2.0  2.200000e+09  0.07  0.00  0.00
1  0.0      0.0680    0.200  0.7  3.200000e+08  0.00  0.13  0.00
2  0.0      2.4800    2.020  0.2  2.700000e+07  0.00  0.00  0.58
3  0.0      2.0000    1.000  0.3  2.500000e+05  0.00  0.00  0.00

# Base Equation

$\sigma_{ag} \phi_g = \chi_g + \sigma_s^{(g-1) \rightarrow g}$

$\lambda = k_{eff} = \sum_{g^\prime = 0}^{3} \nu \sigma_{g^\prime} \phi_{g^\prime}$

# Solve for $\lambda$

In [6]:
# Initial guess for flux (for each group)
flux = np.ones(4)

In [10]:
abs_matrix = np.diag(df['sigma-a'])
print(abs_matrix)

[[0.072 0.    0.    0.   ]
 [0.    0.2   0.    0.   ]
 [0.    0.    2.02  0.   ]
 [0.    0.    0.    1.   ]]


In [12]:
for i in la.eig(abs_matrix):
    print(i)

[0.072 0.2   2.02  1.   ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
production_matrix = np.array([
    df['nu-sigma_f'],
    df['s->1'],
    df['s->2'],
    df['s->3']
])

In [18]:
production_matrix

array([[0.0055, 0.068 , 2.48  , 2.    ],
       [0.07  , 0.    , 0.    , 0.    ],
       [0.    , 0.13  , 0.    , 0.    ],
       [0.    , 0.    , 0.58  , 0.    ]])

In [19]:
for i in la.eig(production_matrix):
    print(i)

[ 0.37610698+0.j         -0.05345627+0.32183545j -0.05345627-0.32183545j
 -0.26369443+0.j        ]
[[-0.97654211+0.j         -0.96383558+0.j         -0.96383558-0.j
   0.92432141+0.j        ]
 [-0.18175134+0.j          0.0338854 +0.2040083j   0.0338854 -0.2040083j
  -0.24536923+0.j        ]
 [-0.06282168+0.j          0.07798087-0.02663992j  0.07798087+0.02663992j
   0.12096577+0.j        ]
 [-0.09687823+0.j         -0.06943631-0.12900101j -0.06943631+0.12900101j
  -0.26606609+0.j        ]]
