In [103]:
from nn4 import NN
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [74]:
train = pd.read_csv('data/processed/train.csv')
val = pd.read_csv('data/processed/val.csv')

In [75]:
train['NotSpam'] = 1 - train['spam']
val['NotSpam'] = 1 - train['spam']

In [76]:
xcols = train.columns[:-2]
ycols = train.columns[-2:]

In [77]:
x = train[xcols].values
y = train[ycols].values
s = MinMaxScaler().fit(x)

In [78]:
xtr = s.transform(x)
ytr = y

In [79]:
x = val[xcols].values
y = val[ycols].values
xv = s.transform(x)
yv = y

In [80]:
net = NN(xtr.shape[1], 1, 5, ytr.shape[1])

In [81]:
for epoch in range(1):
    for ix in range(xtr.shape[0]):
        net.train(xtr[ix], ytr[ix, 0], lr=1.0)

In [82]:
type(xtr)

numpy.ndarray

In [83]:
xtr.shape

(2761, 57)

In [84]:
xtr[0].shape

(57,)

In [85]:
[net.predict(x) for x in xv]

[[0.2798301234420091],
 [0.2800244996656363],
 [0.27930134555768626],
 [0.27955014418230717],
 [0.2793359268960903],
 [0.278897148201066],
 [0.2800066065091491],
 [0.27909038730683655],
 [0.27941608519058964],
 [0.2789380614807296],
 [0.2790793861997678],
 [0.27908865351151996],
 [0.27980521968582645],
 [0.27935865741773613],
 [0.27927312935897625],
 [0.27900885429674355],
 [0.2790299151544817],
 [0.27896657047998297],
 [0.27910833479009783],
 [0.2798021063989955],
 [0.278493988342856],
 [0.2788653651453972],
 [0.2790048183272065],
 [0.27962151547626724],
 [0.27900158768133354],
 [0.27895591642679274],
 [0.2796888336364643],
 [0.2791196747123229],
 [0.2788984270020881],
 [0.27930986231358307],
 [0.28009627571849316],
 [0.27941503285488295],
 [0.27898541647411684],
 [0.27923342260492556],
 [0.27997649051680956],
 [0.27947904315299726],
 [0.27897791135744904],
 [0.27899066121771326],
 [0.27957006630120934],
 [0.2789403323603941],
 [0.27900775019989865],
 [0.27893693184681473],
 [0.279330

In [86]:
net.layers

In [87]:
[n.weights for n in net.layers[0].neurons]

[array([ 0.02705361, -0.00970349,  0.05968419,  0.01344157,  0.02771086,
         0.01402464,  0.04231586,  0.022813  ,  0.02229887,  0.01169007,
         0.05023444,  0.00624274,  0.01406759,  0.00389245,  0.0152721 ,
         0.02596397,  0.05012172,  0.01631944,  0.0634832 ,  0.00207029,
         0.07802097,  0.00780987,  0.04455082,  0.02778457, -0.04074083,
        -0.01742934, -0.03304764, -0.03742645, -0.00347427, -0.01949851,
        -0.00620551, -0.0182364 ,  0.00024509, -0.0208455 , -0.01074927,
        -0.00810329, -0.01079496, -0.00286308, -0.00207155, -0.01558508,
        -0.01291415, -0.01380561, -0.02211512, -0.00326594, -0.00556   ,
        -0.01105451,  0.00252968, -0.00987361, -0.00098542,  0.00173051,
        -0.01134732,  0.01898038,  0.03308162,  0.00865656,  0.00658169,
         0.05187184,  0.02569353,  0.18970644]),
 array([ 2.64081336e-02, -4.66467682e-03,  4.43046284e-02,  1.04970814e-02,
         2.22566451e-02,  3.05316685e-02,  2.70571114e-02,  2.28644930e-

In [88]:
[n.weights for n in net.layers[1].neurons]

[array([-0.41141528, -0.40705958, -0.40364833, -0.39576848, -0.39632362,
        -0.76281507]),
 array([-0.41210938, -0.40874904, -0.41101445, -0.3992262 , -0.40100156,
        -0.75186233]),
 array([-0.40035226, -0.40687783, -0.39468205, -0.39465897, -0.40902003,
        -0.76531148]),
 array([-0.40586409, -0.4073216 , -0.40507099, -0.39674211, -0.39876051,
        -0.76384597]),
 array([-0.40142173, -0.39979079, -0.40661689, -0.40949246, -0.39976569,
        -0.75972565])]

In [89]:
[n.weights for n in net.layers[2].neurons]

[array([-0.21713996, -0.22035045, -0.21914805, -0.21430997, -0.21518747,
        -0.80335921])]

In [90]:
net = NN(xtr.shape[1], 5, 5, ytr.shape[1])

In [97]:
for epoch in range(10):
    for ix in range(xtr.shape[0]):
        net.train(xtr[ix], ytr[ix, 0], lr=50.0)

In [98]:
[net.predict(x) for x in xv]

[[0.0018518744947601184],
 [0.001851874494759539],
 [0.001851874494752916],
 [0.0018518744947576707],
 [0.0018518744947514875],
 [0.00185187449475495],
 [0.001851874494754195],
 [0.0018518744947509098],
 [0.0018518744947558024],
 [0.0018518744947535154],
 [0.0018518744947553197],
 [0.0018518744947519032],
 [0.0018518744947608014],
 [0.0018518744947506325],
 [0.0018518744947488017],
 [0.0018518744947547696],
 [0.0018518744947600085],
 [0.0018518744947542624],
 [0.0018518744947533016],
 [0.0018518744947532296],
 [0.0018518744947498018],
 [0.0018518744947525056],
 [0.0018518744947520474],
 [0.0018518744947505059],
 [0.0018518744947553032],
 [0.0018518744947539423],
 [0.001851874494758401],
 [0.0018518744947513828],
 [0.0018518744947566312],
 [0.0018518744947507277],
 [0.0018518744947527044],
 [0.0018518744947537533],
 [0.001851874494752637],
 [0.0018518744947506802],
 [0.0018518744947525138],
 [0.0018518744947544265],
 [0.0018518744947536698],
 [0.0018518744947573931],
 [0.001851874494752

In [99]:
from utility import PCA

In [105]:
pca = PCA(n_components=0.9).fit(xtr)

In [106]:
xpc = pca.transform(xtr)

In [107]:
net_pc = NN(ninputs=xpc.shape[1], nhidden=5, hiddenwidth=5, noutputs=1)

In [113]:
for epoch in range(10):
    for ix in range(xpc.shape[0]):
        net_pc.train(xpc[ix], ytr[ix, 0], lr=5.0)

In [109]:
[net_pc.predict(x) for x in xv]

IndexError: index 35 is out of bounds for axis 0 with size 35

In [110]:
pca.n_components_

34

In [114]:
[n.weights for n in net_pc.layers[0].neurons]

[array([-4.55127389e-03,  3.70653337e-03,  6.11690720e-03, -8.39333704e-03,
         1.67587764e-03,  1.96524671e-03, -6.58174241e-03, -4.06884801e-03,
        -9.43552751e-03,  3.61565816e-03,  3.94094069e-03,  2.66702367e-05,
        -3.90153172e-03, -8.25416533e-03,  9.48484843e-03, -8.39578575e-03,
        -7.56511724e-03, -8.87766382e-03, -7.57990421e-03,  6.96739572e-03,
        -9.22638235e-03, -8.01743850e-03, -8.62870488e-03, -8.09663436e-03,
        -3.50462052e-03,  8.73794100e-03,  6.75202605e-04, -2.45145035e-03,
        -6.51735542e-03, -1.38389180e-03,  3.41942655e-03,  6.00141364e-03,
         1.55433829e-03,  3.79216230e-04,  6.45688596e-03]),
 array([-0.00312704, -0.00615212,  0.00421905, -0.00037382,  0.00894132,
        -0.00140277,  0.00690502,  0.00661686,  0.00817879, -0.0040213 ,
         0.00617919,  0.00530435, -0.00094306,  0.00857805, -0.00292938,
         0.00968628,  0.00798544, -0.00594776, -0.00412353,  0.00904531,
         0.00701361,  0.00732359,  0.00