# Homework Number 01

In [1]:
import numpy as np

In [16]:
test_mat = np.array([
    [1., 2., 3.],
    [4, 5, 6],
    [7, 8, 9],
    [11, 0, 19],
    [2, 9, 0]
])

In [23]:
print(test_mat)

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 11.   0.  19.]
 [  2.   9.   0.]]


In [33]:
np.set_printoptions(precision=4)

In [34]:
print('std: {}'.format(np.array([np.std(test_mat[:,i], ddof=1) for i in range(test_mat.shape[1])])))
print('mean: {}'.format(np.array([np.mean(test_mat[:,i]) for i in range(test_mat.shape[1])])))

std: [ 4.062   3.8341  7.3007]
mean: [ 5.   4.8  7.4]


## A. Write a "function" m-file called `zscore1` that scales a data matrix so that each column has a unit variance and zero mean and returns the scaling parameters: mean, and standard deviation

In [35]:
def zscore1(mat):
    stds = []
    means = []
    
    for i in range(mat.shape[1]):
        v = mat[:,i]
        s = np.std(v, ddof=1)
        m = np.mean(v)
        
        stds.append(s)
        means.append(m)
        
        v = (v - m) / s
        
        mat[:,i] = v
    
    return(mat, stds, means)

In [36]:
zscore1(test_mat)

(array([[-0.9847, -0.7303, -0.6027],
        [-0.2462,  0.0522, -0.1918],
        [ 0.4924,  0.8346,  0.2192],
        [ 1.4771, -1.2519,  1.5889],
        [-0.7385,  1.0954, -1.0136]]),
 [4.0620192023179804, 3.8340579025361627, 7.3006848993775915],
 [5.0, 4.7999999999999998, 7.4000000000000004])