# NE 579 Homework Number 2: Data Statistics

Import required libaries

In [21]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy.io as sio
from scipy.stats import trim_mean, skew, kurtosis

Load the data from file

In [2]:
data_file = sio.loadmat('hwkdata.mat')
print(data_file.keys())

dict_keys(['__header__', '__version__', '__globals__', 'x', 'y'])


In [3]:
X = data_file['x']
y = data_file['y']
print(f'Input data shape:\t{X.shape}\n'
      f'Output data shape:\t{y.shape}')

Input data shape:	(252, 14)
Output data shape:	(252, 1)


Calculate statistical properties of the data:
- Maximum
- Minimum
- Mean
- Median
- 20% trimmed mean
- Standard deviation
- Variance
- Skewness
- Kurtosis

Maximum

X

In [4]:
np.max(X, axis=0)

array([ 81.  , 363.15,  77.75,  48.9 ,  51.2 , 136.2 , 148.1 , 147.7 ,
        87.3 ,  49.1 ,  33.9 ,  45.  ,  34.9 ,  21.4 ])

y

In [6]:
np.max(y, axis=0)

array([45.1])

Minimum

X

In [7]:
np.min(X, axis=0)

array([ 22. , 118.5,  29.5,  18.1,  31.1,  79.3,  69.4,  85. ,  47.2,
        33. ,  19.1,  24.8,  21. ,  15.8])

y

In [8]:
np.min(y, axis=0)

array([0.])

Mean

X

In [10]:
np.mean(X, axis=0)

array([ 44.88492063, 178.92440476,  70.14880952,  25.43690476,
        37.99206349, 100.82420635,  92.55595238,  99.9047619 ,
        59.40595238,  38.59047619,  23.10238095,  32.2734127 ,
        28.66388889,  18.2297619 ])

y

In [11]:
np.mean(y, axis=0)

array([18.93849206])

Median

X

In [12]:
np.median(X, axis=0)

array([ 43.  , 176.5 ,  70.  ,  25.05,  38.  ,  99.65,  90.95,  99.3 ,
        59.  ,  38.5 ,  22.8 ,  32.05,  28.7 ,  18.3 ])

y

In [13]:
np.median(y, axis=0)

array([19.])

20% trimmed mean

X

In [48]:
trim_mean(X, .2, axis=0)

/Users/jrpowers-luhn/miniconda3/envs/579/lib/python3.6/site-packages/scipy/stats/stats.py:2831: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.mean(atmp[sl], axis=axis)


array([ 44.44078947, 176.55361842,  70.25      ,  25.05986842,
        37.92894737, 100.12763158,  91.80789474,  99.32828947,
        59.13092105,  38.49144737,  22.91381579,  32.16118421,
        28.69934211,  18.21776316])

In [16]:
trim_mean(y, .2, axis=0)

/Users/jrpowers-luhn/miniconda3/envs/579/lib/python3.6/site-packages/scipy/stats/stats.py:2831: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.mean(atmp[sl], axis=axis)


array([18.86578947])

Standard deviation

X

In [17]:
np.std(X, axis=0)

array([12.57701082, 29.3307901 ,  3.65558099,  3.64086527,  2.4260852 ,
        8.41373177, 10.76166054,  7.14982914,  5.2395251 ,  2.4070145 ,
        1.69152717,  3.0152732 ,  2.01667787,  0.93173074])

y

In [18]:
np.std(y, axis=0)

array([7.73546169])

Variance

X

In [19]:
np.var(X, axis=0)

array([158.18120118, 860.29524766,  13.36327239,  13.25589994,
         5.88588939,  70.79088231, 115.81333759,  51.12005669,
        27.4526233 ,   5.79371882,   2.86126417,   9.09187248,
         4.06698964,   0.86812217])

y

In [20]:
np.var(y, axis=0)

array([59.83736757])

Skewness

X

In [22]:
skew(X)

array([ 0.28183067,  1.19807685, -5.35287991,  1.55239101,  0.54932508,
        0.6774921 ,  0.83341904,  1.48820106,  0.81631331,  0.51366304,
        2.24168861,  0.28382759, -0.21802506,  0.27993485])

y

In [23]:
skew(y)

array([0.14338879])

Kurtosis

X

In [24]:
kurtosis(X)

array([-0.43193939,  5.14182358, 58.34569713,  6.55632326,  2.64223799,
        0.94408639,  2.18073601,  7.30021682,  2.5894009 ,  1.01687492,
       11.68578418,  0.46494688,  0.82550054,  0.36415485])

y

In [25]:
kurtosis(y)

array([-0.32445733])

Some graphs

In [33]:
np.ceil(np.round(np.sqrt(X.shape[1])))

4.0

In [35]:
np.ceil(X.shape[1] / np.ceil(np.round(np.sqrt(X.shape[1]))))

4.0

In [1]:
f, ax = plt.subplots(4, 4, figsize=(20,15), sharey=True)
for i in range(4):
    for j in range(4):
        ax[i,j].hist(X[:,i*3+j], bins=25)
plt.show()

NameError: name 'plt' is not defined