In [1]:
import numpy as np

In [61]:
class Layer():
    def __init__(self, ninputs, noutputs):
        self.weights = np.random.random((ninputs+1, noutputs))
    
    def predict(self, x):
        x = np.atleast_2d(x)
        o = np.atleast_2d(np.ones_like(x[:,0])).T

        xs = np.hstack([x, o])

        self.out = self.transfer(xs.dot(self.weights))
        return self.out
    
    def transfer(self, x):
        return 1 / (1 - np.exp(-x))

In [65]:
class OutputLayer(Layer):
    def transfer(self, x):
        return x

In [72]:
class NN():
    def __init__(self, ninputs, nhidden=1, hidden_width=5, noutputs=1):
        self.layers = [Layer(ninputs, hidden_width)]
        for _ in range(nhidden-1):
            self.layers.append(Layer(hidden_width, hidden_width))
        self.outlayer = OutputLayer(hidden_width, noutputs)
    
    def predict(self, x):
        x = np.atleast_2d(x)
        for l in self.layers:
            x = l.predict(x)
        return self.outlayer.predict(x)

    def backprop(self, xt, yt, lr=0.5):
        yp = self.predict(xt)
        delta_v = lr * (yt - yp) @ self.layers[0].out
        
        delta_w = lr * (yt - yp) @ self.outlayer.weights.T
        delta_w = delta_w @ 
        
        self.layers[0] += delta_w
        self.outlayer += delta_v

In [73]:
net = NN(3)

In [74]:
net.layers

In [75]:
net.predict(np.arange(3))

array([[6.25406991]])

In [76]:
net.predict(np.arange(6).reshape(-1, 3))

array([[6.25406991],
       [4.53310081]])

In [77]:
net.backprop(np.arange(3).reshape(-1, 3), np.atleast_2d(5).T)

ValueError: shapes (1,6) and (1,5) not aligned: 6 (dim 1) != 1 (dim 0)

In [60]:
net.preds

[array([[0, 1, 2]]),
 array([[1.42906921, 1.06654051, 1.19603523, 1.06866209, 1.62906445]])]