# NE597: Linear Algebra Homework \#1

In [35]:
import numpy as np
np.set_printoptions(precision=3)

## 1.3

In [36]:
A = np.matrix(
    [
        [8, 0, -3, 4],
        [5, 5, 8, -7],
        [3, -2, -1, 0],
        [0, 7, 5, 4]
    ]
)
B = np.matrix(
    [
        [-3, 1, 1, 10],
        [3, 4, 15, 12],
        [0, -4, -8, 9],
        [2, 1, 1, 2]
    ]
)

### a

In [37]:
2*A

matrix([[ 16,   0,  -6,   8],
        [ 10,  10,  16, -14],
        [  6,  -4,  -2,   0],
        [  0,  14,  10,   8]])

### b

In [38]:
A + B

matrix([[ 5,  1, -2, 14],
        [ 8,  9, 23,  5],
        [ 3, -6, -9,  9],
        [ 2,  8,  6,  6]])

### c

In [39]:
A*B

matrix([[-16,  24,  36,  61],
        [-14, -14,   9, 168],
        [-15,  -1, -19,  -3],
        [ 29,  12,  69, 137]])

### d

In [40]:
B - A

matrix([[-11,   1,   4,   6],
        [ -2,  -1,   7,  19],
        [ -3,  -2,  -7,   9],
        [  2,  -6,  -4,  -2]])

### e

In [41]:
B*A

matrix([[-16,  73,  66,  21],
        [ 89,  74,  68,  32],
        [-44,  59,  21,  64],
        [ 24,  17,  11,   9]])

### f

In [42]:
A.trace()

matrix([[16]])

### g

In [43]:
B.trace()

matrix([[-5]])

### h

In [44]:
np.trace(A ** 2 * B)

1809

## 1.16

Let $\mathbf{A}$ be an $n \times n$ matrix and let $\mathbf{B}=\mathbf{A} + \mathbf{A}^T$ and $\mathbf{C} = \mathbf{A} - \mathbf{A}^T$. Show that:

1. $\mathbf{B}$ is symmetric and $\mathbf{C}$ is skew-symmetric.
2. Every $n \times n$ matrix can be represented as a sum of a symmetric and skew-symmetric matrix.

## 1.17

For each of the following pairs of matrices, find an elementary matrix $\mathbf{E}$ such that $\mathbf{EA}=\mathbf{B}$.

### a

In [45]:
A = np.matrix([
    [3, 8],
    [5, 16]
])
B = np.matrix([
    [12, 32],
    [5, 16]
])

In [46]:
np.round(B * np.linalg.inv(A))

matrix([[ 4., -0.],
        [ 0.,  1.]])

### b

In [47]:
A = np.matrix([
    [7, 6, 3],
    [2, 0, 9],
    [-8, 7, 4]
])
B = np.matrix([
    [-8, 7, 4],
    [2, 0, 9],
    [7, 6, 3]
])

In [48]:
np.round(B * np.linalg.inv(A))

matrix([[ 0.,  0.,  1.],
        [ 0.,  1.,  0.],
        [ 1., -0.,  0.]])

### c

In [49]:
A = np.matrix([
    [1, 4, 5, 9],
    [0, 6, 2, 1],
    [-4, 5, 2, -3],
    [3, -3, 9, 0]
])
B = np.matrix([
    [1, 4, 5, 9],
    [6, 0, 20, 1],
    [-4, 5, 2, -3],
    [3, -3, 9, 0]
])

In [50]:
np.round(B * np.linalg.inv(A))

matrix([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  2.],
        [ 0.,  0.,  1., -0.],
        [ 0.,  0.,  0.,  1.]])

## 1.27

Solve the following systems of linear equations:

### a

In [51]:
A = np.array([
    [2, 3, 1],
    [-2, 1, 1],
    [4, -3, 4]
])
B = np.array([11, 3, 10])
print(np.linalg.solve(A, B))

[ 1.  2.  3.]


### b

In [52]:
A = np.array([
    [2, 3, 4, 1],
    [0, 1, 1, -3],
    [0, 0, 4, 5],
    [1, 0, -1, 0]
])
B = np.array([24, 18, 10, 7])
print(np.linalg.solve(A, B))

[ 19.8  -19.52  12.8   -8.24]


### c

In [53]:
A = np.array([
    [3, 2, 1],
    [-2, 1, -1],
    [2, -1, 2]
])
B = np.array([0, 2, -1])
print(np.linalg.solve(A, B))

[-1.  1.  1.]


### d

In [54]:
A = np.array([
    [1, 2, -2],
    [2, 5, 1],
    [1, 3, 4]
])
B = np.array([9, 9, -2])
print(np.linalg.solve(A, B))

[ 3.  1. -2.]


### e

In [55]:
A = np.array([
    [3, -4, 4],
    [3, 2, 37],
    [-4, 6, -5]
])
B = np.array([-15, 0, 25])
print(np.linalg.solve(A, B))

[ 7.  8. -1.]


### f

In [56]:
A = np.array([
    [3, 1, 1],
    [1, 2, -3],
    [0, -4, -6]
])
B = np.array([0, -4, 26])
print(np.linalg.solve(A, B))

[ 1.971 -4.743 -1.171]


## 1.35

Let A be a 8 × 8 symmetric matrix with $a_{ij} =2(0.9)^{|i −j|}$ and B be another 8 × 8 symmetric matrix with $b_{ij} =3(0.8)^{|i −j|}$. Find:

In [57]:
A = np.array([[2 * 0.9 ** np.abs(i - j) for j in range(8)] for i in range(8)])
B = np.array([[3 * 0.8 ** np.abs(i - j) for j in range(8)] for i in range(8)])

### a

$c_{ij}$, and $d_{ij}$ if $C =AB$ and $D =BA$.

In [58]:
C = A * B
print(C)

[[ 6.     4.32   3.11   2.239  1.612  1.161  0.836  0.602]
 [ 4.32   6.     4.32   3.11   2.239  1.612  1.161  0.836]
 [ 3.11   4.32   6.     4.32   3.11   2.239  1.612  1.161]
 [ 2.239  3.11   4.32   6.     4.32   3.11   2.239  1.612]
 [ 1.612  2.239  3.11   4.32   6.     4.32   3.11   2.239]
 [ 1.161  1.612  2.239  3.11   4.32   6.     4.32   3.11 ]
 [ 0.836  1.161  1.612  2.239  3.11   4.32   6.     4.32 ]
 [ 0.602  0.836  1.161  1.612  2.239  3.11   4.32   6.   ]]


In [59]:
D = B * A
print(D)

[[ 6.     4.32   3.11   2.239  1.612  1.161  0.836  0.602]
 [ 4.32   6.     4.32   3.11   2.239  1.612  1.161  0.836]
 [ 3.11   4.32   6.     4.32   3.11   2.239  1.612  1.161]
 [ 2.239  3.11   4.32   6.     4.32   3.11   2.239  1.612]
 [ 1.612  2.239  3.11   4.32   6.     4.32   3.11   2.239]
 [ 1.161  1.612  2.239  3.11   4.32   6.     4.32   3.11 ]
 [ 0.836  1.161  1.612  2.239  3.11   4.32   6.     4.32 ]
 [ 0.602  0.836  1.161  1.612  2.239  3.11   4.32   6.   ]]


### b

Trace(A), Trace(B), and Trace(AB)

In [60]:
print(np.trace(A))

16.0


In [61]:
print(np.trace(B))

24.0


In [62]:
print(np.trace(A*B))

48.0


## 2.1

### a. Compute the determinate of the following matrices

In [63]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.linalg.det(A))

-9.51619735393e-16


In [64]:
B = np.array([
    [1, 0, -1],
    [0, 1, 2],
    [1, 2, -1]
])
print(np.linalg.det(B))

-4.0


### b. Show that $det(AB) = det(A) det(B)$

In [78]:
np.linalg.det(A.dot(B)) == np.linalg.det(A) * np.linalg.det(B)

False

In [77]:
np.linalg.det(A.dot(B))

0.0

In [79]:
np.linalg.det(A) * np.linalg.det(B)

3.8064789415719762e-15

In [82]:
print(A.dot(B))

[[ 4  8  0]
 [10 17  0]
 [16 26  0]]
