In [173]:
from __future__ import division
import numpy as np
import numpy.linalg as la
from copy import deepcopy

# Problem 3.3

In [180]:
x1 = np.array([1, 2, -2])
x2 = np.array([-1, 3, 1])
x3 = np.array([-2, 1, 3])
x4 = np.array([1, -2, 5])
x = np.array([x1, x2, x3, x4]).astype(np.float64)
print(x)
print(x.shape)

[[ 1.  2. -2.]
 [-1.  3.  1.]
 [-2.  1.  3.]
 [ 1. -2.  5.]]
(4, 3)


In [181]:
def gauss_jordan(y):
    z = deepcopy(y)
    print(z[0])
    print(la.norm(z[0]))
    print(z[0] / la.norm(z[0]))
    print((z[0] / la.norm(z[0])).shape)
    z[0, :] = z[0, :] / la.norm(z[0])

    print(z)

In [182]:
gauss_jordan(x)

[ 1.  2. -2.]
3.0
[ 0.33333333  0.66666667 -0.66666667]
(3,)
[[ 0.33333333  0.66666667 -0.66666667]
 [-1.          3.          1.        ]
 [-2.          1.          3.        ]
 [ 1.         -2.          5.        ]]


In [183]:
t = x[0] / la.norm(x[0])
print(t)

[ 0.33333333  0.66666667 -0.66666667]


In [184]:
for i in range(len(t)):
    print("x[0, {}] = t[{}]".format(i, i))
    print("x[0, {}] = {}".format(i, t[i]))
    x[0, i] = t[i]

x[0, 0] = t[0]
x[0, 0] = 0.333333333333
x[0, 1] = t[1]
x[0, 1] = 0.666666666667
x[0, 2] = t[2]
x[0, 2] = -0.666666666667


In [185]:
x

array([[ 0.33333333,  0.66666667, -0.66666667],
       [-1.        ,  3.        ,  1.        ],
       [-2.        ,  1.        ,  3.        ],
       [ 1.        , -2.        ,  5.        ]])