In [7]:
import numpy as np
from numpy.polynomial.legendre import leggauss
from scipy.special import legendre
from scipy.integrate import trapz

In [2]:
leggauss(2)

(array([-0.57735027,  0.57735027]), array([ 1.,  1.]))

In [3]:
leggauss(3)

(array([-0.77459667,  0.        ,  0.77459667]),
 array([ 0.55555556,  0.88888889,  0.55555556]))

In [4]:
leggauss(4)

(array([-0.86113631, -0.33998104,  0.33998104,  0.86113631]),
 array([ 0.34785485,  0.65214515,  0.65214515,  0.34785485]))

In [24]:
x = np.linspace(-1, 1, 1000000)

In [25]:
trapz(legendre(2)(x), x)

1.9999861142205866e-12

In [26]:
x

array([-1.      , -0.999998, -0.999996, ...,  0.999996,  0.999998,  1.      ])

In [27]:
legendre(2)(0)

-0.50000000000000011

In [34]:
f = lambda y: y**2
trapz(f(x), x)

0.66666666666800023

In [29]:
def x2(x):
    return x * x

In [30]:
trapz(x2(x), x)

0.66666666666800023

In [31]:
leggauss(12)

(array([-0.98156063, -0.90411726, -0.76990267, -0.58731795, -0.3678315 ,
        -0.12523341,  0.12523341,  0.3678315 ,  0.58731795,  0.76990267,
         0.90411726,  0.98156063]),
 array([ 0.04717534,  0.10693933,  0.16007833,  0.20316743,  0.23349254,
         0.24914705,  0.24914705,  0.23349254,  0.20316743,  0.16007833,
         0.10693933,  0.04717534]))

# Question 2

Solve for $\int_{-1}^1 \mathrm{e}^{-2x} dx$

In [35]:
def f(x):
    return np.exp(-2 * x)

In [36]:
x, y = leggauss(2)

In [37]:
vals = f(x)

In [38]:
vals.dot(y)

3.4882249603075559

In [39]:
x = np.linspace(-1, 1, 100000)
trapz(f(x), x)

3.6268604083306091